language: csharp
solution: NEAT_Visualizer.sln
addons:
  apt:
    packages:
      - gtk-sharp2
install:
  - nuget restore NEAT_Visualizer.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release NEAT_Visualizer.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./NEAT_Visualizer.BusinessTest/bin/Release/NEAT_Visualizer.BusinessTest.dll

