configuration:
  - Release
before_build:
  - nuget restore
after_build:
  - cd NEAT_Visualizer\bin\Release
  - 7z a NEAT_Visualizer.zip *.exe *.dll
artifacts:
  - path: NEAT_Visualizer\bin\Release\NEAT_Visualizer.zip
    name: NEAT_Visualizer
deploy:
  provider: GitHub
  auth_token:
    secure: wvQeRLDr/jbJxn7YtxE4W59hmbpMLjN9ReA05MqZKoXN171i3i3IEF9pkZk7QA6P
  artifact: NEAT_Visualizer
  on:
    appveyor_repo_tag: true

